### ISSUE TITLE
Selenium2TestCase->execute() not very obvious

### ISSUE THREAD

**Issue by xrstf** [giorgiosironi/phpunit-selenium#160]
I tried to execute some JavaScript in my page and therefore the ```execute()``` method, as it is described in v1.2.7:

> @method string execute($javaScriptCode) Injects arbitrary JavaScript in the page and returns the last

This made me write:

``` php
<?
protected function injectErrorHandler() {
	return $this->execute("
window._errors = [];
window.onerror = function(args) {
	var args = arguments, len = args.length, i = 0;

	for (; i < len; ++i) {
		window._errors.push(args[i]);
	}
};

return 1;
");
}
```

This led to exceptions about invalid JSON parameters. Parameters should be an arry, so I changed my code to

``` php
<?
protected function injectErrorHandler() {
	return $this->execute(array("/* snip */"));
}
```

This worked in PHPUnit, but made Selenium crash because it couldn't convert the list to a map. After (finally) consuling the WireProtocol, it was clear that I had to write

``` php
<?
protected function injectErrorHandler() {
	return $this->execute(array('script' => "/* snip */"));
}
```

Now the JavaScript is executed, but directly followed by another exception in Selenium. It turns out that I **must** define the arguments, even if there are none.

``` php
<?
protected function injectErrorHandler() {
	return $this->execute(array(
		'script' => "/* snip */",
		'args' => array()
	));
}
```

Was I supposed to know that all magic GenericPost commands need to have a proper params array that I have to get from the WireProtocol specs? Is this just an oversight? Is this implementation simply not yet finished and therefore no dedicated command class exists?

**Comment by chrisplusplus** [comment]
Anyone know why I get this exception when trying to use the execute method?
command:
        $this->execute(array(
            'script' => $js,
            'args'   => array()
        ));

error given:
Method execute not defined.

I suspect it has something to do with the proper classes not being included, but I was under the impression that they were included because I am able to run other Selenium commands just fine.
I'm using PHPUnit+Selenium within within Yii.  Thanks!

**Comment by giorgiosironi** [comment]
Which class are you extending?

**Comment by chrisplusplus** [comment]
I'm using yii. Which I finally discovered had an abstract class extending
SeleniumTestCase rather than Selenium2TestCase (which extends phpunit).
After changing that, and then realizing the code I wrote for selenium RC no
longer works,  the execute command works as expected. Sorry for the noob
questions here.  I'm just now beginning my journey using Selenium/PHPUnit.

**Comment by giorgiosironi** [comment]
Glad this was solved for you
